version: 1.0.{build}

# you can use {branch} name in version format too
# version: 1.0.{build}-{branch}

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

# Skipping commits with particular message or from specific user
skip_commits:
  message: /\[skip appveyor\]/      # Regex for matching commit message

# Do not build feature branch with open Pull Requests
# skip_branch_with_pr: true

# Maximum number of concurrent jobs for the project
max_jobs: 1

# Build worker image (VM template)
image: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

# clone directory
clone_folder: c:\projects\myproject

# fetch repository as zip archive
shallow_clone: true                 # default is "false"

# set clone depth
clone_depth: 5                      # clone entire repository history if not defined

# environment variables
environment:
  PYTHON: C:\Python27
  MINICONDA: C:\Miniconda3-x64
  APPVEYOR_RDP_PASSWORD: ein_t3st1ing_admin

matrix:
  fast_finish: true

# build cache to preserve files/folders between builds
cache:
#  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  # - C:\python37\
  - C:\ProgramData\chocolatey\lib
  - C:\ProgramData\chocolatey\bin
  - '%LocalAppData%\NuGet\Cache'    # NuGet < v3
  - '%LocalAppData%\NuGet\v3-cache' # NuGet v3

# scripts that run after cloning repository
install:
  # to run script as a PowerShell command prepend it with ps:
  # - if not exist %userprofile%\local mkdir %userprofile%\local
  # - if not exist %userprofile%\.emacs.d mkdir %userprofile%\.emacs.d
  # - copy C:\projects\myproject\tools\appveyor.init.el %userprofile%\.emacs.d\init.el
  # - copy C:\projects\myproject\tools\appveyor.init.el %userprofile%\.emacs
  - set PATH=%userprofile%\.cask\bin;C:\msys64\usr\bin;%PYTHON%\Scripts;%PATH%
  - "%PYTHON%\\python.exe -m pip install --upgrade pip"
  - "%PYTHON%\\python.exe -m pip install -r test_requirements.txt"
  - jupyter kernelspec list
  - ipython --version
  - curl --version
  - choco install emacs64
  - emacs --version
  - curl -fsSL https://raw.githubusercontent.com/millejoh/cask/appveyor-build/go | python


#---------------------------------#
#       build configuration       #
#---------------------------------#

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - invoke clean
  - invoke test-compile

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  # - ps: $env:PATH = "$(cask exec-path);$env:PATH"
  # - ps: $env:EMACSLOADPATH = $(cask load-path)
  - invoke test-unit
  - invoke test-int
  # - bash -lc "cd /c/projects/myproject ; make test"

# Uncomment the following if you need to connect to build after it finishes to
# troubleshoot any issues.
# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
