(source gnu)
(source melpa-stable)

(package "mocker" "0.3.1"
         "mocking framework for emacs.")

(depends-on "eieio" "1.4")

(development
  (depends-on "ert-runner")
  (depends-on "mocker")
  (depends-on "shut-up"))
