* Description
This is a elisp library for websocket clients to talk to websocket
servers, and for websocket servers to accept connections from
websocket clients. This library is designed to be used by other
library writers, to write apps that use websockets, and is not useful
by itself.

An example of how to use the library is in the
[[https://github.com/ahyatt/emacs-websocket/blob/master/websocket-functional-test.el][websocket-functional-test.el]] file.

This library is compatible with emacs 23 and 24, although only emacs
24 support secure websockets.

* Version release checklist

Each version that is released should be checked with this checklist:

- [ ] All ert test passing
- [ ] Functional test passing on emacs 23 and 24
- [ ] websocket.el byte compiling cleanly.

* Existing clients:

- [[https://github.com/tkf/emacs-ipython-notebook][Emacs IPython Notebook]]
- [[https://github.com/syohex/emacs-realtime-markdown-viewer][Emacs Realtime Markdown Viewer]]
- [[https://github.com/jscheid/kite][Kite]]
- [[https://github.com/ancane/markdown-preview-mode][Markdown-preview-mode]]

If you are using this module for your own emacs package, please let me
know by editing this file, adding your project, and sending a pull
request to this repository.

